[package]
name = "hotpot-dev"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
hotpot-core = { path = "../hotpot-core" }
tokio = { workspace = true }
futures = { workspace = true }
notify = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
walkdir = { workspace = true }
libc = "0.2"

[dev-dependencies]
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }
